CREATE DATABASE mapiCS;

CREATE TABLE users (
  id VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255)
);


CREATE TABLE maps (
  id VARCHAR(255) PRIMARY KEY,
  heading VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  theme VARCHAR(255) NOT NULL,
  creator_id VARCHAR(255) REFERENCES users(id) ON DELETE CASCADE
);



CREATE TABLE locations (
  id VARCHAR(255) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  longitude DOUBLE PRECISION NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  type VARCHAR(255) NOT NULL,
  map_id VARCHAR(255) REFERENCES maps(id) ON DELETE CASCADE
);