
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  avatar VARCHAR(255)
);


CREATE TABLE maps (
  id VARCHAR(255) NOT NULL,
  heading VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  theme VARCHAR(255) NOT NULL,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
);



CREATE TABLE locations (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  longitude VARCHAR(255) NOT NULL,
  latitude VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
);